3 atualizar interacao cadastro
Alohomora-team/2019.2-AlohomoraBot pull request #16
Opened 2019-10-22 15:18 UTC by VictorJorgeFGA

## Issue 3
    
Resolve #3 

## Descrição

- Novo passo na interação com bot durante o cadastro para registrar um áudio do usuário dizendo o próprio nome
- Alterações por todo o código abrangendo os requerimentos do pylint

## Tipo de mudança

- [ ] Bugfix
- [x] Funcionalidade nova
- [ ] Mudança de funcionalidade

## Comentários adicionais

O PR está sendo submetido sem testes. Os testes serão delegados para a issue #6

2019-10-27 01:27 UTC, Bumbleblo submitted a review, later dismissed

2019-10-27 01:29 UTC, Bumbleblo commented
Gostei as classes no checks.py. Acredito que um pouco mais de esforço empregado isso pode virar uma hierarquia para resolver os problemas de analise.

2019-11-02 04:13 UTC, Bumbleblo submitted a review, later dismissed

2019-11-02 04:13 UTC, Bumbleblo commented
Falta somente arrumar os conflitos

2019-11-03 16:29 UTC, VictorJorgeFGA commented
Para possibilitar o PR estarei retirando (apenas comentados) os campos do pylintrc que requerem docstrings, Preciso fazer isso pois é inviável eu escrever mais de 50 docstrings apenas pra passar esse PR jurássico.

2019-11-08 03:51 UTC, Bumbleblo requested changes
Só não vai rolar. Eu posso entender que não da pra fazer todas docstrings porém tirar a regra é inviável.

2019-11-08 03:51 UTC, Bumbleblo commented on bot/feedback.py
> +LOGGER = logging.getLogger(LOG_NAME)
porque isso ? No python palavras em caixa alta são constantes portanto isso ta ferindo o idioma da linguagem.

2019-11-09 02:38 UTC, VictorJorgeFGA commented on bot/feedback.py
> +LOGGER = logging.getLogger(LOG_NAME)
Apenas fazendo o que o pylint tava recomendando.

2019-11-11 16:35 UTC, VictorJorgeFGA commented
Por incompetência minha não tem como dar um rollback efetivo. Estarei futuramente abrindo um novo Pull Request pra uma branch atualizada que cumpre a issue.

2019-11-11 16:35 UTC, closed without merging