Criação do bancos de dados para o bot
Alohomora-team/2019.2-AlohomoraBot pull request #26
Opened 2019-11-03 00:10 UTC by baraky

## Descrição

As implementações fornecidas por esses PR disponibiliza um banco de dados, a fim de armazenar dados pertinentes no uso do bot. Seu principal objetivo é possibilitar o envio de mensagens utilizando do 'chat_id' dos usuários guardados no banco.

## Tipo de mudança

- [ ] Criação das models: Resident, Visitor e Admin;
- [ ] Criação do CRUD de cada model;
- [ ] Testes;
- [ ] CHANGELOG.

2019-11-08 03:48 UTC, Bumbleblo requested changes
Você colocou o arquivo da database no git. : )

2019-11-08 13:16 UTC, baraky commented
> Você colocou o arquivo da database no git. : )

O database.db é o arquivo gerado pelo models.py, com as tabelas e etc. Ele está vazio, acredito que sem esse arquivo toda vez que alguém for utilizar o banco teria que dar um `python models.py`. É necessário tirar mesmo assim?

2019-11-09 12:31 UTC, Bumbleblo commented
Sim, realmente é melhor tirar esse cara.

2019-11-09 12:49 UTC, Bumbleblo approved these changes
Show, sem o .db podemos prosseguir.

2019-11-09 18:16 UTC, merged