24 adicionar grupos de comandos
Alohomora-team/2019.2-AlohomoraBot pull request #33
Opened 2019-11-13 02:10 UTC by RodrigoTCLima

## Issue
    
Resolve #24 
## Descrição
Foram criadas duas novas interações /morador e /visitante que listam os comandos do que cada um tem acesso.

Ps.: não há listagem quanto aos comandos de Administradores pois ainda não há interações com o bot que sejam para eles.

## Tipo de mudança

- [ ] Bugfix
- [X] Funcionalidade nova
- [ ] Mudança de funcionalidade

## Comentários adicionais

Informações complementares

2019-11-13 03:17 UTC, baraky requested changes

2019-11-13 03:17 UTC, baraky commented on bot/main.py
>      update.message.reply_text('Para dar um feedback pro nosso serviço, digite /feedback')
O objetivo de fazer a listagem dos comandos é diminuir o número de mensagens do _/start_. Remova as repetições que ficaram (_/cadastrar_, _/autorizar_, etc.).

Acho uma boa ideia também deixar no _/start_ o _/feedback_ e tirar na listagem dos comandos de morador e visitante, visto que é um comando compartilhado entre todos os usuários do bot.

2019-11-13 03:18 UTC, baraky commented on bot/main.py
>      update.message.reply_text('Para dar um feedback pro nosso serviço, digite /feedback')
Mude 'morador' e 'visitante' para 'resident' e 'visitor'

2019-11-13 08:07 UTC, Bumbleblo commented on bot/main.py
>      update.message.reply_text('Para dar um feedback pro nosso serviço, digite /feedback')
Lembra que o usuário final vai consumir o software em portugues

2019-11-13 13:51 UTC, baraky commented on bot/main.py
>      update.message.reply_text('Para dar um feedback pro nosso serviço, digite /feedback')
> Lembra que o usuário final vai consumir o software em portugues

Exato, acabei não deixando claro mas estava referindo ao nome das funções.

2019-11-14 03:41 UTC, Bumbleblo commented
Alguma novidade neste trabalho ? Percebi que as revisões não foram resolvidas, os conflitos e o lint ainda não foi atualizado.

2019-11-14 22:58 UTC, Bumbleblo commented
Alô ?

2019-11-14 23:00 UTC, RodrigoTCLima commented
Tentarei atender as vossas requisições hoje, ontem estava ocupado.

2019-11-15 12:57 UTC, baraky approved these changes

2019-11-15 12:58 UTC, merged