4 Criar interação feedback
Alohomora-team/2019.2-AlohomoraBot pull request #9
Opened 2019-10-15 23:16 UTC by luis-furtado

## Issue
    
#4 

## Descrição

Adicionada a interação de feedback
Integração com a API feita (query que envia uma mutation para a API com o novo feedback).

## Tipo de mudança

- [ ] Bugfix
- [x] Funcionalidade nova
- [ ] Mudança de funcionalidade

2019-10-16 03:57 UTC, Bumbleblo commented
link da issue

2019-10-16 18:32 UTC, VictorJorgeFGA requested changes
Parece estar ok a funcionalidade. Mas faltam os testes e adicionar as mudanças no changelog. Sei que testes pro bot é um rolê, mas coloca pelo menos as mudanças no changelog

2019-10-16 21:13 UTC, baraky commented
> Parece estar ok a funcionalidade. Mas faltam os testes e adicionar as mudanças no changelog. Sei que testes pro bot é um rolê, mas coloca pelo menos as mudanças no changelog

Este repositorio não possui o arquivo CHANGELOG, deve-se criar um?

2019-10-17 14:58 UTC, VictorJorgeFGA commented
Sim. No corpo da issue pede o changelog. Basta criar um arquivo de changelog seguindo esse padrão: https://keepachangelog.com/en/1.0.0/

2019-10-18 16:37 UTC, luis-furtado commented
@VictorJorgeFGA o CHANGELOG foi adicionado.

2019-10-19 21:46 UTC, luis-furtado commented
@Bumbleblo resolvi os `conflitos`. A branch está pronta para `merge`.

2019-10-20 15:09 UTC, VictorJorgeFGA approved these changes

2019-10-20 15:11 UTC, merged